# Generated by Django 4.0.4 on 2022-05-26 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('happiness', '0002_alter_happiness_date_alter_happiness_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='happiness',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='happiness', to=settings.AUTH_USER_MODEL),
        ),
    ]
